# These are the fields that are inheritted either by every note.
---
new_field_type:
  field_name: uuid
  field_type: uuid
  required: true
  assigned: system
  overwrite: false
  reassign: false
...


---
new_field_type:
  field_name: time_created
  field_type: time_stamp
  required: true
  assigned: system
  overwrite: false
  reassign: false
...


---
new_field_type:
  field_name: time_modified
  field_type: time_stamp
  required: true
  assigned: system
  reassign: false
...


---
new_field_type:
  field_name: note_type
  field_type: word
  required: true
  assigned: system
  reassign: false
...


---
new_field_type:
  field_name: body_format
  field_type: word
  assigned: system
  reassign: false
...


---
new_field_type:
  field_name: collection
  field_type: single_line
  required: true
  assigned: system
  reassign: false
...

# These are the fields that are inheritted either by every collection.
---
new_field_type:
  field_name: collection_type
  field_type: word
  required: true
  assigned: system
  reassign: false
...


---
new_field_type:
  field_name: collection_name
  field_type: single_line
  required: true
  reassign: false
...

---
new_field_type:
  field_name: tags
  field_type: list of words
...


---
new_field_type:
  field_name: title
  field_type: single_line
...


---
new_field_type:
  field_name: aliases
  field_type: list of single_line
...


---
new_field_type:
  field_name: internal_links
  field_type: list of uuid or referencer
...


---
new_field_type:
  field_name: description
  field_type: list of single_line
...


---
new_field_type:
  field_name: notes
  field_type: list of single_line
...


---
new_field_type:
  field_name: subcollections
  field_type: list of uuid or referencer
...


---
new_field_type:
  field_name: collected_notes
  field_type: list of uuid or referencer
...


---
new_note_type:
  note_type: minimal_note
  metadata_fields:
    - uuid
    - time_created
    - time_modified
    - note_type
    - body_format
...


---
new_note_type:
  note_type: basic_note
  extends: minimal_note # Not required as it is the default value
  metadata_fields:
    - tags
    - title
    - aliases
    - internal_links
    - field_name: body_format
      required: true
  body_specification:
    body_content: text
    body_format:
      format: any
      required: true
...

---
new_note_type:
  note_type: basic_metadata
  matadata_fields:
    - tags
    - internal_links
    - description
    - notes
...


---
new_collection_type:
  collection_type: minimal_collection
  metadata:
    - uuid
    - time_created
    - time_modified
    - collection_type
...
